In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv("ps1.csv")

In [3]:
data.columns

Index(['momweight', 'babyweight', 'momheight'], dtype='object')

In [7]:
data.sort_values(by = 'momweight')

       momweight  babyweight  momheight
41858         72        2750         61
46640         75        2270         48
32749         75        2501         59
9245          75        2295         62
10664         75        3100         53
13347         75        3147         62
14615         75        3140         60
45010         76        3515         54
1779          78        3941         60
37546         78        2135         60
22123         78        2420         61
47583         80        3317         62
30493         80        3190         60
45709         80        2975         57
15218         80        3090         57
1475          80        2818         57
38681         80        2863         60
48415         80        2240         58
8173          80        2551         60
48648         80        2580         59
31288         80        2240         64
3721          80        2892         60
7339          80        2385         59
10388         80        3487         60
18341         80        2781         60
19025         80        2105         59
40184         80        2539         59
47498         80        4020         60
33059         80        2920         59
20590         81        2803         55
...          ...         ...        ...
40576        232        3843         72
33289        232        3742         70
10471        232        3175         70
4945         232        3300         70
47618        234        3935         70
24389        234        3090         72
44534        234        3685         70
20077        235        4441         72
37153        235        4110         71
20621        235        4008         72
10490        235        4026         72
36019        235        3459         73
23001        235        3657         70
6929         235        3685         72
239          240        3640         72
1379         240        3739         71
27882        240        4021         74
11960        240        3842         73
5146         242        4125         72
45393        242        3266         76
46279        242        3895         71
37525        244        4196         72
1360         245        2860         72
7263         245        3459         72
33135        248        4241         72
27775        252        3320         73
46230        260        3950         74
3229         260        3572         74
38611        265        3695         77
35896        279        3192         78

[48871 rows x 3 columns]

In [5]:
data = data.drop(["index", "level_0"], axis = 1)

KeyError: "['index' 'level_0'] not found in axis"

In [ ]:
quantiles = np.arange(.1, .91, .1)
deciles = data['momweight'].quantile(quantiles)
deciles

In [ ]:
d1 = []
d2 = []
d3 = []
d4 = []
d5 = []
d6 = []
d7 = []
d8 = []
d9 = []
d10 = []
for i in range(len(data['momweight'])):
    if data["momweight"][i] < 108:
        d1.append(data.iloc[i])
    elif data["momweight"][i] >= 108 and data["momweight"][i] < 115:
        d2.append(data.iloc[i])
    elif data["momweight"][i] >= 115 and data["momweight"][i] < 121:
        d3.append(data.iloc[i])
    elif data["momweight"][i] >= 121 and data["momweight"][i] < 128:
        d4.append(data.iloc[i])
    elif data["momweight"][i] >= 128 and data["momweight"][i] < 133:
        d5.append(data.iloc[i])
    elif data["momweight"][i] >= 133 and data["momweight"][i] < 140:
        d6.append(data.iloc[i])
    elif data["momweight"][i] >= 140 and data["momweight"][i] < 147:
        d7.append(data.iloc[i])
    elif data["momweight"][i] >= 147 and data["momweight"][i] < 158:
        d8.append(data.iloc[i])
    elif data["momweight"][i] >= 158 and data["momweight"][i] < 172:
        d9.append(data.iloc[i])
    elif data["momweight"][i] > 172:
        d10.append(data.iloc[i])

In [ ]:
d1 = pd.DataFrame(d1)
d2 = pd.DataFrame(d2)
d3 = pd.DataFrame(d3)
d4 = pd.DataFrame(d4)
d5 = pd.DataFrame(d5)
d6 = pd.DataFrame(d6)
d7 = pd.DataFrame(d7)
d8 = pd.DataFrame(d8)
d9 = pd.DataFrame(d9)
d10 = pd.DataFrame(d10)

In [ ]:
mean_deciles = []
mean_deciles.append(np.mean(d1))
mean_deciles.append(np.mean(d2))
mean_deciles.append(np.mean(d3))
mean_deciles.append(np.mean(d4))
mean_deciles.append(np.mean(d5))
mean_deciles.append(np.mean(d6))
mean_deciles.append(np.mean(d7))
mean_deciles.append(np.mean(d8))
mean_deciles.append(np.mean(d9))
mean_deciles.append(np.mean(d10))
mean_deciles = pd.DataFrame(mean_deciles)

In [ ]:
plt.scatter(mean_deciles["momweight"],mean_deciles["babyweight"], alpha = 0.7)

In [ ]:
np.percentile(data["momweight"],[10,25,50,75,90])

In [ ]:
dataPercentile = []
#Retreives the observations where mother's weight is the corresponding 
for i in data:
    for j in np.percentile(data["momweight"],[10,25,50,75,90]):
        dataPercentile.append(data[data["momweight"] == j])

In [ ]:
dp10 =np.mean(dataPercentile[0])
dp25 = np.mean(dataPercentile[1])
dp50 = np.mean(dataPercentile[2])
dp75 = np.mean(dataPercentile[3])
dp90 = np.mean(dataPercentile[4])

In [ ]:
dp= []
dp.append(dp10)
dp.append(dp25)
dp.append(dp50)
dp.append(dp75)
dp.append(dp90)

In [ ]:
dp = pd.DataFrame(dp)

In [ ]:
plt.figure(figsize = (9,9))
plt.scatter(mean_deciles["momweight"],mean_deciles["babyweight"], alpha = 0.7)
plt.scatter(dp["momweight"], dp["babyweight"], color = 'red')
plt.xticks([100,125,150,175,200])
plt.yticks(np.arange(3000,3800,100))
plt.title("Bin Scatter: Baby's Weight vs. Mother's Weight")
plt.ylabel("Baby's Weight in Grams")
plt.xlabel("Mother's Weight(Pre-pregnancy) in Pounds")

**2 B)**

In [6]:
buckets = np.arange(95,max(data["momweight"]),5)
buckets

array([ 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155,
       160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220,
       225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275])

In [8]:
df=pd.DataFrame({'A':np.random.random(20),'B':np.random.random(20)})

In [20]:
df = df.sort_values('B')
bins =  np.arange(0,1.0,0.155)
ind = np.digitize(df['B'],bins)
df.head()

           A         B
9   0.787115  0.009789
10  0.593397  0.027422
13  0.127960  0.045695
14  0.457212  0.062034
7   0.576806  0.068775